version: "3"

services:
  api:
    build: ./backend
    command: bash -c "black . && isort -v . && flake8 -v . && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    tty: true
  web:
    build: ./frontend
    command: bash -c "if [ ! -d node_modules ]; then npm install; fi && npm run format && npm run lint && npm run start --host 0.0.0.0"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    tty: true

