# Generated by Django 4.2.2 on 2023-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("comment", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
